---
title: "DAV_FinalProject_map"
author: "Weijun Zhu"
date: "November 22, 2019"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r}
library(dplyr)
library(ggplot2)
library(rjson)
library(jsonlite)
library(leaflet)
library(RCurl)
library(leaflet.extras)
library(tidyverse)
```

```{r}
data <- read.csv("C:/Users/zhuwe/Desktop/DAV_FinalProject/DAV_FinalProject/7282_2.csv", header=T)
```

```{r}
str(data)
```

Filter California(CA) from data
```{r}
data_CA <- data %>%
  filter(province == 'CA')
```

# leaflet()
```{r}
CA <- leaflet(data_CA) %>%
  addTiles() %>%
  addCircleMarkers(lng = ~longitude,
                   lat = ~latitude,
                   weight = 10)
CA
```

# HeatMap
```{r}
library(leaflet.extras)
leaflet(data_CA) %>% 
  addTiles() %>%
  addProviderTiles(providers$CartoDB.DarkMatter) %>%
  addWebGLHeatmap(lng=~longitude, lat=~latitude, size = 60000)
```

# choropleth map
## Cited from: https://rstudio.github.io/leaflet/choropleths.html
```{r}
m <- leaflet(data_CA) %>%
  setView(-96, 37.8, 4) %>%
  addProviderTiles("MapBox", options = providerTileOptions(
    id = "mapbox.light",
    accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN')))
```

```{r}
m %>% addCircles()
```


```{r}
bins <- c(0,1,2,3,4,5)
pal <- colorNumeric("YlOrRd", domain = data_CA$reviews.rating)

m %>% addTiles() %>%
  addCircles(
    weight = 10,
    opacity = 6,
    color = ~pal(data_CA$reviews.rating),
    dashArray = "3",
    fillOpacity = 0.7)
```

```{r}
m %>% addTiles() %>%
  addCircles(
    weight = 10,
    opacity = 1,
    color = ~pal(data_CA$reviews.rating),
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE))
```


```{r}
labels <- sprintf(
  "<strong>%s</strong><br/>%g rating<sup></sup>",
  data_CA$city, data_CA$reviews.rating
) %>% lapply(htmltools::HTML)

m <- m %>% addTiles() %>%
  addCircles(
    weight = 10,
    opacity = 1,
    color = ~pal(data_CA$reviews.rating),
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"))
```

```{r}
m %>% addLegend(pal = pal, values = ~reviews.rating, opacity = 0.7, title = NULL,
  position = "bottomleft")
```

